# Rust formatting configuration for MCP Server
# https://rust-lang.github.io/rustfmt/

# Edition
edition = "2021"

# Line width
max_width = 100
comment_width = 100
wrap_comments = true

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_indent = "Block"
reorder_imports = true

# Function definitions
fn_params_layout = "Tall"
fn_call_width = 80
fn_single_line = false

# Control flow
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"

# Formatting
indent_style = "Block"
hard_tabs = false
tab_spaces = 4

# Trailing
trailing_comma = "Vertical"
trailing_semicolon = true
match_block_trailing_comma = true

# Blank lines
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0

# Strings
format_strings = true
format_code_in_doc_comments = true

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Misc
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
match_arm_blocks = true
force_multiline_blocks = false
where_single_line = false
newline_style = "Auto"

# Reorder
reorder_impl_items = true

# Space
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false

# Use
use_small_heuristics = "Default"

# Unstable features (require nightly)
# Uncomment if using nightly Rust
# unstable_features = false
